---
- name: Backup and zip directories for specified games
  hosts: windows_vm
  gather_facts: yes
  roles:
    - game_backup
  vars:
    game_list:
      - name: 'gta5'
        target_dir: 'C:\\labs'
      - name: 'wukong'
        target_dir: 'C:\\Wukong_Labs'
      # Add more games with specific target directories as needed

  tasks:
    - name: Debug game_list
      debug:
        msg: "Game list: {{ game_list }}"
      tags:
        - always

    - name: Debug ansible_run_tags
      debug:
        msg: "Ansible run tags: {{ ansible_run_tags }}"
      tags:
        - always
    
    # - name: Convert ansible_run_tags to list
    #   set_fact:
    #     ansible_run_tags_list: "{{ ansible_run_tags | split(',') }}"
    #   tags:
    #     - always

    # - name: Debug converted ansible_run_tags
    #   debug:
    #     msg: "Converted ansible run tags: {{ ansible_run_tags_list }}"
    #   tags:
    #     - always

    
    - name: Backup and zip directories for selected games
      block:
        - name: Ensure game-specific backup directory exists
          win_file:
            path: "{{ backup_base_dest }}\\{{ item.name }}"
            state: directory

        - name: Print the file destination directory
          debug:
            msg: "The backup zip file will be saved to: {{ backup_base_dest }}\\{{ item.name }}\\{{ item.name }}-{{ timestamp }}.zip"

        - name: Create a zip file from the directory
          win_command: |
            powershell Compress-Archive -Path "{{ item.target_dir }}" -DestinationPath "{{ backup_base_dest }}\\{{ item.name }}\\{{ item.name }}-{{ timestamp }}.zip"
      loop: "{{ game_list }}"
      when: item.name in ansible_run_tags
