---
- name: Backup and zip directories for specified games
  hosts: windows_vm
  gather_facts: yes
  roles:
    - game_backup
  vars:
    game_list:
      - name: 'gta5'
        target_dir: 'C:\\labs'
      - name: 'wukong'
        target_dir: 'C:\\Wukong_Labs'
      # Add more games with specific target directories as needed

  tasks:
    - name: Set tags to include
      set_fact:
        included_games: "{{ ansible_run_tags.split(',') }}"

    - name: Debug ansible_run_tags
      debug:
        msg: "ansible_run_tags: {{ ansible_run_tags }}"

    - name: Set tags to include
      set_fact:
        included_games: "{{ ansible_run_tags if ansible_run_tags is iterable else ansible_run_tags.split(',') }}"

    - name: Debug the included games list
      debug:
        msg: "Included games: {{ included_games }}"
    
    - name: Backup and zip directories for selected games
      include_role:
        name: game_backup
      vars:
        game_name: "{{ item.name }}"
        target_dir: "{{ item.target_dir }}"
        zip_dest: "{{ backup_base_dest }}\\{{ item.name }}\\{{ item.name }}-{{ timestamp }}.zip"
      with_items: "{{ game_list }}"
      when: item.name in included_games
