---
- name: Install Chocolatey and manage packages on Windows
  hosts: windows
  tasks:
    - name: Ensure Chocolatey is installed
      win_chocolatey:
        name: chocolatey
        state: present
      become: yes
      tags:
        - chocolatey

    - name: Install packages using Chocolatey
      chocolatey.chocolatey.win_chocolatey:
        name: "{{ item }}"
        state: present
      loop:
        - git
        - vscode
      tags:
        - packages
