---
- name: Backup Games on Windows
  hosts: windows_vm
  gather_facts: no

  vars:
    backup_dir: "C:\path\to\your\backup\directory"
    games:
      - name: gta5
        save_dir: "C:\path\to\gta5\saves"
      - name: wukong
        save_dir: "C:\path\to\wukong\saves"
      # Add more games here

  tasks:
    - name: Create backup directory if it doesn't exist
      ansible.windows.win_file:
        path: "{{ backup_dir }}"
        state: directory

    - name: Backup specified games
      ansible.windows.win_copy:
        src: "{{ item.save_dir }}"
        dest: "{{ backup_dir }}\{{ item.name }}.zip"
        force: yes
      loop: "{{ games }}"
      when: item.name in tags

    - name: Compress backup files (optional)
      ansible.windows.win_command: powershell -Command "Compress-Archive -Path '{{ backup_dir }}\*.zip' -DestinationPath '{{ backup_dir }}\all_games.zip'"
      when: "gta5" in tags or "wukong" in tags  # Adjust based on your tags
