---
- name: Backup Game Saves on Windows
  hosts: windows_vm
  vars:
    backup_dir: "C:\\GameBackup"
    games:
      - name: GTA5
        save_dir: "C:\\Labs\\GTA5"
      - name: Wukong
        save_dir: "C:\\Labs\\Wukong"
      # Add more games here as needed

  tasks:
    - name: Create main backup directory if it doesn't exist
      win_file:
        path: "{{ backup_dir }}"
        state: directory
      tags:
        - always

    - name: Get current timestamp
      win_shell: Get-Date -Format "yyyyMMdd-HHmmss"
      register: timestamp
      tags:
        - always

    - name: Create backup_game.yml on remote
      win_copy:
        dest: "{{ backup_dir }}\\backup_game.yml"
        content: |
          - name: Create game-specific backup directory
            win_file:
              path: "{{ backup_dir }}\\{{ game.name }}"
              state: directory

          - name: Backup and compress game saves
            win_shell: |
              $ErrorActionPreference = "Continue"
              if (Test-Path "{{ game.save_dir }}") {
                Compress-Archive -Path "{{ game.save_dir }}" -DestinationPath "{{ backup_dir }}\\{{ game.name }}\\{{ game.name }}-{{ timestamp.stdout }}.zip" -Force
                if (Test-Path "{{ backup_dir }}\\{{ game.name }}\\{{ game.name }}-{{ timestamp.stdout }}.zip") {
                  Write-Output "Backup successful"
                } else {
                  Write-Output "Backup failed"
                }
              } else {
                Write-Output "Save directory does not exist"
              }
            register: backup_result

          - name: Report backup status
            debug:
              msg: "Backup for {{ game.name }}: {{ backup_result.stdout_lines[-1] }}"

    - name: Process game backups
      win_shell: |
        Invoke-Expression -Command "& '{{ backup_dir }}\\backup_game.yml'"
      loop: "{{ games }}"
      loop_control:
        loop_var: game
      tags:
        - "{{ game.name }}"
