---
- name: Backup Game Saves on Windows
  hosts: windows_vm
  vars:
    backup_dir: "C:\\GameBackup"
    games:
      - name: GTA5
        save_dir: "C:\\Labs\\GTA5"
      - name: Wukong
        save_dir: "C:\\Labs\\Wukong"
      # Add more games here as needed

  tasks:
    - name: Create main backup directory if it doesn't exist
      win_file:
        path: "{{ backup_dir }}"
        state: directory
      tags:
        - always

    - name: Create game-specific backup directories
      win_file:
        path: "{{ backup_dir }}\\{{ item.name }}"
        state: directory
      loop: "{{ games }}"
      tags:
        - "{{ item.name }}"

    - name: Get current timestamp
      win_shell: Get-Date -Format "yyyyMMdd-HHmmss"
      register: timestamp
      tags:
        - always

    - name: Backup and compress game saves
      win_compress:
        path: "{{ item.save_dir }}"
        dest_path: "{{ backup_dir }}\\{{ item.name }}\\{{ item.name }}-{{ timestamp.stdout }}.zip"
        format: zip
      loop: "{{ games }}"
      ignore_errors: yes
      tags:
        - "{{ item.name }}"

    - name: Check if zip file was created
      win_stat:
        path: "{{ backup_dir }}\\{{ item.name }}\\{{ item.name }}-{{ timestamp.stdout }}.zip"
      register: zip_stat
      loop: "{{ games }}"
      tags:
        - "{{ item.name }}"

    - name: Report backup status
      debug:
        msg: "Backup for {{ item.item.name }} was {% if item.stat.exists %}successful{% else %}unsuccessful (possibly due to missing save directory){% endif %}"
      loop: "{{ zip_stat.results }}"
      loop_control:
        label: "{{ item.item.name }}"
      tags:
        - "{{ item.item.name }}"
