---
- name: Backup and zip a directory on Windows
  hosts: windows_vm
  vars:
    target_dir: 'C:\\Labs'
    backup_base_dest: 'C:\\GameSave'
    game_name: 'labs'  # Replace with your game name
    timestamp: "{{ ansible_date_time.iso8601_basic }}"  # Timestamp for the zip file name
    zip_dest: "{{ backup_base_dest }}\\{{ game_name }}\\{{ game_name }}-{{ timestamp }}.zip"

  tasks:
    - name: Ensure backup base directory exists
      win_file:
        path: "{{ backup_base_dest }}"
        state: directory

    - name: Ensure game-specific backup directory exists
      win_file:
        path: "{{ backup_base_dest }}\\{{ game_name }}"
        state: directory
        
    - name: Print the file destination directory
      debug:
        msg: "The backup zip file will be saved to: {{ zip_dest }}"

    - name: Create a zip file from the directory
      win_command: |
        powershell Compress-Archive -Path "{{ target_dir }}" -DestinationPath "{{ backup_base_dest }}\\{{ game_name }}\\{{ game_name }}-{{ timestamp }}.zip"
