---
- name: Backup Game Saves on Windows
  hosts: windows_vm
  vars:
    backup_dir: "C:\\GameBackup"
    games:
      - name: GTA5
        save_dir: "C:\\Labs\\GTA5"
      - name: Wukong
        save_dir: "C:\\Labs\\Wukong"
      # Add more games here as needed

  tasks:
    - name: Create main backup directory if it doesn't exist
      win_file:
        path: "{{ backup_dir }}"
        state: directory
      tags:
        - always

    - name: Get current timestamp
      win_shell: Get-Date -Format "yyyyMMdd-HHmmss"
      register: timestamp
      tags:
        - always

    - name: Create backup_game.yml on remote
      win_template:
        src: backup_game.yml.j2
        dest: "{{ backup_dir }}\\backup_game.yml"
      vars:
        timestamp: "{{ timestamp.stdout }}"
      tags:
        - always

    - name: Execute backup tasks
      win_shell: |
        Invoke-Expression -Command "& '{{ backup_dir }}\\backup_game.yml'"
      loop: "{{ games }}"
      loop_control:
        loop_var: game
      tags:
        - "{{ game.name }}"
