---
- name: Backup Game Saves on Windows
  hosts: windows_vm
  vars:
    backup_dir: "C:\\GameBackup"
    games:
      - name: GTA5
        save_dir: "C:\\Labs\\GTA5"
      - name: Wukong
        save_dir: "C:\\Labs\\Wukong"

  tasks:
    - name: Create main backup directory if it doesn't exist
      community.windows.win_file:
        path: "{{ backup_dir }}"
        state: directory
      tags:
        - always

    - name: Get current timestamp
      win_shell: Get-Date -Format "yyyyMMdd-HHmmss"
      register: timestamp
      tags:
        - always

    - name: Backup game saves
      community.windows.win_archive:
        path: "{{ item.save_dir }}"
        dest: "{{ backup_dir }}\\{{ item.name }}\\{{ item.name }}-{{ timestamp.stdout }}.zip"
        force: yes
      loop: "{{ games }}"
      loop_control:
        label: "{{ item.name }}"
      tags: "{{ item.name }}"
