- hosts: win
  gather_facts: no
  tasks:
    - name: test powershell
      win_shell: |
                whoami
      register: result_get_host

    - name: display result_get_host
      debug:
        var: result_get_host
